project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/esthertangz/esthertangz.github.io
      - icon: linkedin 
        href: https://www.linkedin.com/in/esther-zeonee-tang/
format:
  html:
    theme: cosmo
    css: styles.css

